baseURL = "https://yalunpeng.com/"

defaultContentLanguage = "zh"
languageCode           = "zh"

title = "yalunpeng"

copyright = 'å¤‡æ¡ˆå·: èœ€ICPå¤‡17003301å·-1'

disableKinds = ["taxonomy", "term"]
enableEmoji  = true

[author]
    headline = "A Neuroscience PhD Candidate . ğŸ’¬"
    image    = "logo.jpeg"
    name     = "å½­é›…ä¼¦(Yalun Peng)"

    links = [
        { facebook = { href = "mailto:yp1017@nyu.edu", "text" = "yp1017@nyu.edu", icon = "flickr" } },
    #    { github = { href = "https://github.com/akushonkamen", text = "GitHub", target = "_self" } },
        { stack-exchange = { href = "https://alpha-quant.com.cn", text = "ä½œå“", target = "_self", icon = "stack-exchange" } },
        { google = { href = "https://resume.yalunpeng.com/", text = "ç®€å†", target = "_self", icon = "instagram" } },
    ]

[module]
    [module.hugoVersion]
        extended = false
        min      = "0.86.1"
